Migrate `Hurl.BrowserSelector` to WinUI3
U-C-S/Hurl pull request #174
Opened 2024-11-09 03:11 UTC by U-C-S

2025-02-27 05:57 UTC, U-C-S commented
Waiting on winappsdk 1.7

2025-04-08 05:23 UTC, U-C-S commented
For trayicon: https://github.com/HavenDV/H.NotifyIcon

2025-04-16 00:31 UTC, Jay-o-Way requested changes

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Hurl.Selector.csproj
> +    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250205002" GeneratePathProperty="true" />
Have a look at the new XAML TitleBar in 1.7.1

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Hurl.Selector.csproj
> +    <PackageReference Include="WinUIEx" Version="2.5.1" />
No need for this. Recommend to remove.

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/MainWindow.cs
> +                SystemBackdrop = new MicaBackdrop(),
Mica is originally intended for long(er) live windows. I think acrylic is good. Also this can be set in XAML.

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/MainWindow.cs
> +    public void SetContent(UIElement content) => window.Content = content;
Shouldn't be needed if you'd just use MainWindow

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +                                    FontSize="10"
Way too small. Try to stick with guidelines (see type ramp)

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +                            Visibility="{Binding ShowAdditionalBtn}">
Binding or x:Bind?

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +            Background="{StaticResource AccentAcrylicBackgroundFillColorBaseBrush}"
Use a ThemeResource for anything that **could** change, depending on light or dark theme.

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +            CornerRadius="6">
Stick with StaticResources

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +            BorderThickness="1.5"
Usually you would use whole numbers

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +                        <FontIcon FontSize="18" Glyph="&#xE8C8;" />
```suggestion
                        <FontIcon FontSize="16" Glyph="&#xE8C8;" />
```

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +                                Tag="settings"
Tags don't match text

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/TimedDefaultPage.xaml
> +            <RowDefinition Height="30" />
32 or Auto

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/TimedDefaultPage.xaml
> +                Background="{StaticResource AccentAcrylicBackgroundFillColorBaseBrush}"
Again, use ThemeResource. Also use a central Style.

2025-04-16 00:31 UTC, Jay-o-Way commented on Source/Hurl.Selector/Pages/TimedDefaultPage.xaml
> +                CornerRadius="4"
Use StaticResources

2025-04-16 05:16 UTC, U-C-S commented
@Jay-o-Way Thanks for a review.

The features I was waiting for, never happened in 1.7 (nor in 1.6, 1.5...) winappsdk (only available in experimental) and nor the fixes for some annoying half-baked-implementations for itemsView or context menu. winui3 repo looks like it's in maintenance mode. 
I dont know if I should still continue working on this.

2025-04-19 20:28 UTC, U-C-S commented on Source/Hurl.Selector/Pages/SelectorPage.xaml
> +                                    FontSize="10"
set to 12 now

2025-04-19 20:29 UTC, U-C-S commented on Source/Hurl.Selector/MainWindow.cs
> +    public void SetContent(UIElement content) => window.Content = content;
Just trying out a different pattern. didn't work as I thought, reverting.

2025-04-19 20:33 UTC, U-C-S commented on Source/Hurl.Selector/Hurl.Selector.csproj
> +    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250205002" GeneratePathProperty="true" />
https://github.com/microsoft/microsoft-ui-xaml/blob/main/specs/TitleBar/titlebar-functional-spec.md

2026-04-30 10:50 UTC, U-C-S commented
- https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/Samples/DeploymentManager/cs-winui/MainWindow.xaml.cs
- https://github.com/microsoft/XamlBehaviors
- https://github.com/microsoft/NativeAOTDependencyHelper

2026-05-02 08:41 UTC, merged